name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
  
      - name: Decode google-nmedia-b3264-firebase-adminsdk-h05v6-955e8d7304.json
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
        run: echo $FIREBASE_SECRET > ./app/google-nmedia-b3264-firebase-adminsdk-h05v6-955e8d7304.json

      - name: Decode constans.kt
        env:
          CONSTANS_SECRET: ${{ secrets.CONSTANS_SERCET }}
        run: echo $CONSTANS_SERCET > ./app/src/main/kotlin/ru/netology/pusher/constans.kt

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
